// Introduction, speaker context and experience controls.
export const experienceCopy={
  "en": {
    "title": "Geeta",
    "introLine": "Arjun lowers his bow.",
    "introBody": "Between two armies, he sees family, teachers and friends among those he must fight. He turns to Krishna.",
    "framing": "Two branches of one family face each other across a vast battlefield. Arjun, a Pandava prince, asks his friend Krishna to drive their chariot between the armies.",
    "language": "Choose your language",
    "enter": "Enter the story",
    "resume": "Continue your journey",
    "restart": "Begin again",
    "soundOn": "Battlefield sound",
    "soundHint": "Sound begins when you enter. You can change its volume or turn it off at any time.",
    "about": "About this retelling",
    "notes": [
      "An original, abridged adaptation of the Bhagavad Gita. The dialogue is adapted; the Sanskrit shlokas are presented separately with verse references.",
      "The translations and artwork reflect interpretive choices. Different traditions understand these teachings in different ways.",
      "The Gita's conversation takes place before the battle begins. Combat, kneeling poses and changing light here are artistic staging, rather than a literal chronology or historical reconstruction.",
      "Scenes include non-graphic battle and discussions of death."
    ],
    "meet": "The voices in this story",
    "voices": {
      "Sanjaya": {
        "role": "The narrator",
        "description": "Dhritarashtra's adviser. Granted divine sight through Vyasa, he recounts Krishna and Arjun's conversation to the king, away from the battlefield.",
        "location": "Narrating to the king"
      },
      "Dhritarashtra": {
        "role": "The king",
        "description": "Father of the Kauravas. He asks Sanjaya what is happening where his sons and their cousins have gathered for war.",
        "location": "Listening at court"
      },
      "Arjun": {
        "role": "The warrior",
        "description": "One of the five Pandava brothers. He is a skilled archer, but the sight of his own family and teachers across the field overwhelms him.",
        "location": "On the chariot"
      },
      "Krishna": {
        "role": "The guide",
        "description": "Arjun's friend and charioteer. He becomes his teacher, and reveals his divine nature as their conversation unfolds.",
        "location": "On the chariot"
      }
    },
    "menu": "Menu",
    "journey": "The journey",
    "intro": "Introduction",
    "dialogue": "Dialogue",
    "shloka": "Shloka",
    "meaning": "Meaning",
    "verseNote": "Browse any verse in this chapter. The adapted dialogue draws on the verse range shown above.",
    "verseUnavailable": "The shloka could not load. You can continue with the dialogue.",
    "who": "Who is speaking?",
    "back": "Previous",
    "next": "Continue",
    "scene": "Scene",
    "look": "Look around",
    "lookHelpDesktop": "Drag to turn · Scroll to zoom · Shift-drag or WASD to move",
    "lookHelpTouch": "One finger to turn · Two fingers to move · Pinch to zoom",
    "returnView": "Return to the chariot",
    "viewFront": "Face to face",
    "viewSide": "Beside the chariot",
    "viewWide": "The whole field",
    "camera": "Camera",
    "light": "Light",
    "storyLight": "Follow the story",
    "dawn": "Dawn",
    "day": "Day",
    "dusk": "Dusk",
    "night": "Night",
    "volume": "Battlefield volume",
    "gentleCamera": "Hold camera still",
    "gentleNote": "Keeps your current viewpoint as the story continues. Turn this off for continuous camera movement.",
    "pause": "Pause scene",
    "play": "Resume scene",
    "settings": "Settings",
    "contents": "Chapters",
    "progress": "Reading progress",
    "complete": "The conversation rests here.",
    "audioPending": "Narration is not available yet.",
    "reading": "Read the story",
    "listening": "Listen",
    "source": "Source & context",
    "close": "Close",
    "moving": "Arriving between the armies",
    "skipArrival": "Skip arrival",
    "showDialogue": "Show dialogue",
    "hideDialogue": "Hide dialogue",
    "readHint": "Continue at your own pace. Looking around does not turn the page.",
    "chapter": "Chapter",
    "preface": "Before the conversation",
    "soundError": "Sound could not start. Tap the sound control to try again.",
    "experienceMode": "Experience mode",
    "passageView": "Passage view",
    "moveCamera": "Move camera",
    "moveLeft": "Move left",
    "moveRight": "Move right",
    "moveForward": "Move forward",
    "moveBack": "Move back",
    "playback": "Playback"
  },
  "hi": {
    "title": "गीता",
    "introLine": "अर्जुन अपना धनुष नीचे रख देते हैं।",
    "introBody": "दो सेनाओं के बीच खड़े अर्जुन को सामने अपने संबंधी, गुरु और मित्र दिखाई देते हैं, जिनसे उन्हें युद्ध करना है। वे कृष्ण की ओर मुड़ते हैं।",
    "framing": "एक ही परिवार की दो शाखाएँ विशाल रणभूमि में आमने-सामने खड़ी हैं। पांडव राजकुमार अर्जुन अपने मित्र कृष्ण से रथ को दोनों सेनाओं के बीच ले चलने को कहते हैं।",
    "language": "अपनी भाषा चुनें",
    "enter": "कथा में प्रवेश करें",
    "resume": "अपनी यात्रा जारी रखें",
    "restart": "फिर से आरंभ करें",
    "soundOn": "रणभूमि की ध्वनि",
    "soundHint": "प्रवेश करते ही ध्वनि शुरू हो जाती है। आप किसी भी समय उसका स्तर बदल सकते हैं या उसे बंद कर सकते हैं।",
    "about": "इस रूपांतरण के बारे में",
    "notes": [
      "भगवद्गीता का एक मौलिक, संक्षिप्त रूपांतरण। संवाद को रूपांतरित किया गया है; संस्कृत श्लोक उनके संदर्भों के साथ अलग से प्रस्तुत हैं।",
      "अनुवाद और कलाकृतियाँ व्याख्या संबंधी चुनावों को दर्शाते हैं। अलग-अलग परंपराएँ इन शिक्षाओं को अलग-अलग तरह से समझती हैं।",
      "गीता का संवाद युद्ध शुरू होने से पहले होता है। यहाँ दिखाया गया युद्ध, घुटनों के बल बैठने की मुद्राएँ और बदलता प्रकाश कलात्मक दृश्य-संयोजन हैं; वे घटनाओं का हूबहू कालक्रम या ऐतिहासिक पुनर्निर्माण नहीं हैं।",
      "दृश्यों में बिना रक्तपात के युद्ध और मृत्यु पर चर्चा शामिल है।"
    ],
    "meet": "इस कथा के स्वर",
    "voices": {
      "Sanjaya": {
        "role": "कथावाचक",
        "description": "धृतराष्ट्र के सलाहकार। व्यास से दिव्य दृष्टि पाकर वे रणभूमि से दूर राजा को कृष्ण और अर्जुन का संवाद सुनाते हैं।",
        "location": "राजा को कथा सुनाते हुए"
      },
      "Dhritarashtra": {
        "role": "राजा",
        "description": "कौरवों के पिता। वे संजय से पूछते हैं कि जहाँ उनके पुत्र और उनके चचेरे भाई युद्ध के लिए एकत्र हुए हैं, वहाँ क्या हो रहा है।",
        "location": "राजदरबार में सुनते हुए"
      },
      "Arjun": {
        "role": "योद्धा",
        "description": "पाँच पांडव भाइयों में से एक। वे कुशल धनुर्धर हैं, लेकिन रणभूमि के उस पार अपने परिवार और गुरुओं को देखकर व्याकुल हो उठते हैं।",
        "location": "रथ पर"
      },
      "Krishna": {
        "role": "मार्गदर्शक",
        "description": "अर्जुन के मित्र और सारथी। वे उनके गुरु बनते हैं और संवाद आगे बढ़ने के साथ अपना दिव्य स्वरूप प्रकट करते हैं।",
        "location": "रथ पर"
      }
    },
    "menu": "मेन्यू",
    "journey": "यात्रा",
    "intro": "परिचय",
    "dialogue": "संवाद",
    "shloka": "श्लोक",
    "meaning": "अर्थ",
    "verseNote": "इस अध्याय का कोई भी श्लोक देखें। रूपांतरित संवाद ऊपर दी गई श्लोक-सीमा पर आधारित है।",
    "verseUnavailable": "श्लोक लोड नहीं हो सका। आप संवाद के साथ आगे बढ़ सकते हैं।",
    "who": "कौन बोल रहे हैं?",
    "back": "पिछला",
    "next": "आगे बढ़ें",
    "scene": "दृश्य",
    "look": "आस-पास देखें",
    "lookHelpDesktop": "घुमाने के लिए ड्रैग करें · ज़ूम के लिए स्क्रॉल करें · खिसकने के लिए Shift के साथ ड्रैग करें या WASD दबाएँ",
    "lookHelpTouch": "घुमाने के लिए एक उँगली · खिसकने के लिए दो उँगलियाँ · ज़ूम के लिए चुटकी की तरह उँगलियाँ पास लाएँ या दूर करें",
    "returnView": "रथ पर लौटें",
    "viewFront": "आमने-सामने",
    "viewSide": "रथ के पास",
    "viewWide": "पूरी रणभूमि",
    "camera": "कैमरा",
    "light": "प्रकाश",
    "storyLight": "कथा के अनुसार",
    "dawn": "भोर",
    "day": "दिन",
    "dusk": "संध्या",
    "night": "रात",
    "volume": "रणभूमि की ध्वनि का स्तर",
    "gentleCamera": "कैमरा स्थिर रखें",
    "gentleNote": "कथा आगे बढ़ने पर भी आपका वर्तमान दृष्टिकोण स्थिर रहता है। कैमरे की निरंतर गति के लिए इसे बंद करें।",
    "pause": "दृश्य रोकें",
    "play": "दृश्य फिर चलाएँ",
    "settings": "सेटिंग्स",
    "contents": "अध्याय",
    "progress": "पढ़ने की प्रगति",
    "complete": "संवाद यहाँ विराम लेता है।",
    "audioPending": "वाचन अभी उपलब्ध नहीं है।",
    "reading": "कथा पढ़ें",
    "listening": "सुनें",
    "source": "स्रोत और संदर्भ",
    "close": "बंद करें",
    "moving": "दो सेनाओं के बीच पहुँच रहे हैं",
    "skipArrival": "आगमन छोड़कर आगे बढ़ें",
    "showDialogue": "संवाद दिखाएँ",
    "hideDialogue": "संवाद छिपाएँ",
    "readHint": "अपनी गति से आगे बढ़ें। आस-पास देखने से पन्ना नहीं बदलता।",
    "chapter": "अध्याय",
    "preface": "संवाद से पहले",
    "soundError": "ध्वनि शुरू नहीं हो सकी। फिर कोशिश करने के लिए ध्वनि नियंत्रण पर टैप करें।",
    "experienceMode": "अनुभव मोड",
    "passageView": "पाठ का दृश्य",
    "moveCamera": "कैमरा खिसकाएँ",
    "moveLeft": "बाएँ खिसकें",
    "moveRight": "दाएँ खिसकें",
    "moveForward": "आगे बढ़ें",
    "moveBack": "पीछे हटें",
    "playback": "प्लेबैक"
  },
  "ja": {
    "title": "ギーター",
    "introLine": "アルジュナは弓を下ろす。",
    "introBody": "両軍の間で、アルジュナは戦う相手の中に親族、師、友人たちの姿を見つけます。彼はクリシュナに向き直ります。",
    "framing": "同じ一族の二つの勢力が、広大な戦場で向かい合っています。パーンダヴァの王子アルジュナは、友クリシュナに戦車を両軍の間へ進めるよう頼みます。",
    "language": "言語を選んでください",
    "enter": "物語へ進む",
    "resume": "旅を続ける",
    "restart": "最初から始める",
    "soundOn": "戦場の音",
    "soundHint": "物語に入ると音が流れます。音量の変更や消音は、いつでもできます。",
    "about": "この再話について",
    "notes": [
      "『バガヴァッド・ギーター』を独自に短く翻案した作品です。対話は翻案であり、サンスクリット語のシュローカは章節番号とともに別に掲載しています。",
      "翻訳とアートワークには、それぞれの解釈が反映されています。これらの教えの理解は、伝統によって異なります。",
      "『ギーター』の対話は戦いが始まる前に行われます。ここでの戦闘、ひざまずく姿、移り変わる光は芸術的な演出であり、出来事の時系列をそのまま示すものでも、歴史的な再現でもありません。",
      "場面には、流血を伴わない戦闘描写と死についての対話が含まれます。"
    ],
    "meet": "この物語の語り手たち",
    "voices": {
      "Sanjaya": {
        "role": "語り手",
        "description": "ドリタラーシュトラの助言者。ヴィヤーサから神の視力を授かり、戦場から離れた王にクリシュナとアルジュナの対話を伝えます。",
        "location": "王に語りかける"
      },
      "Dhritarashtra": {
        "role": "王",
        "description": "カウラヴァ兄弟の父。息子たちとそのいとこたちが戦いのために集まった地で何が起きているのかを、サンジャヤに尋ねます。",
        "location": "宮廷で耳を傾ける"
      },
      "Arjun": {
        "role": "戦士",
        "description": "パーンダヴァ五兄弟の一人。優れた弓の使い手ですが、戦場の向こうに自分の家族や師を見て、心が押しつぶされそうになります。",
        "location": "戦車の上"
      },
      "Krishna": {
        "role": "導き手",
        "description": "アルジュナの友であり、御者。彼の師となり、対話が進むにつれて自らの神性を明かします。",
        "location": "戦車の上"
      }
    },
    "menu": "メニュー",
    "journey": "旅路",
    "intro": "はじめに",
    "dialogue": "対話",
    "shloka": "シュローカ",
    "meaning": "意味",
    "verseNote": "この章のどの詩節も読むことができます。翻案された対話は、上に示した詩節の範囲に基づいています。",
    "verseUnavailable": "シュローカを読み込めませんでした。対話はそのまま読み進められます。",
    "who": "誰が話している？",
    "back": "前へ",
    "next": "続ける",
    "scene": "場面",
    "look": "周りを見渡す",
    "lookHelpDesktop": "ドラッグで向きを変える · スクロールで拡大・縮小 · Shift＋ドラッグまたはWASDで移動",
    "lookHelpTouch": "指1本で向きを変える · 指2本で移動 · ピンチで拡大・縮小",
    "returnView": "戦車に戻る",
    "viewFront": "向かい合う",
    "viewSide": "戦車のそば",
    "viewWide": "戦場全体",
    "camera": "カメラ",
    "light": "光",
    "storyLight": "物語に合わせる",
    "dawn": "夜明け",
    "day": "昼",
    "dusk": "夕暮れ",
    "night": "夜",
    "volume": "戦場の音量",
    "gentleCamera": "カメラを固定",
    "gentleNote": "物語が進んでも現在の視点を保ちます。カメラを滑らかに動かすにはオフにしてください。",
    "pause": "場面を一時停止",
    "play": "場面を再開",
    "settings": "設定",
    "contents": "章一覧",
    "progress": "読書の進み具合",
    "complete": "対話は、ここでひと休みします。",
    "audioPending": "音声はまだ利用できません。",
    "reading": "物語を読む",
    "listening": "聴く",
    "source": "原典と背景",
    "close": "閉じる",
    "moving": "二つの軍の間へ向かっています",
    "skipArrival": "到着の演出をスキップ",
    "showDialogue": "対話を表示",
    "hideDialogue": "対話を隠す",
    "readHint": "自分のペースで読み進めてください。周りを見渡しても、ページは変わりません。",
    "chapter": "章",
    "preface": "対話の前に",
    "soundError": "音を再生できませんでした。音のコントロールをタップして、もう一度お試しください。",
    "experienceMode": "体験モード",
    "passageView": "本文の表示",
    "moveCamera": "カメラを移動",
    "moveLeft": "左へ移動",
    "moveRight": "右へ移動",
    "moveForward": "前へ移動",
    "moveBack": "後ろへ移動",
    "playback": "再生"
  },
  "zh-Hans": {
    "title": "薄伽梵歌",
    "introLine": "阿周那放下了弓。",
    "introBody": "站在两军之间，他发现即将交战的人中有自己的亲人、老师和朋友。他转向克里希纳。",
    "framing": "同一家族的两支势力在辽阔的战场上对峙。般度族王子阿周那请他的朋友克里希纳驾着战车，来到两军之间。",
    "language": "选择语言",
    "enter": "进入故事",
    "resume": "继续旅程",
    "restart": "重新开始",
    "soundOn": "战场音效",
    "soundHint": "进入故事后，声音便会响起。你随时可以调节音量或关闭声音。",
    "about": "关于这次改编",
    "notes": [
      "本作是对《薄伽梵歌》进行的独立创作与精简改编。对话经过改写；梵文颂诗另行呈现，并标注章节出处。",
      "译文与美术体现了诠释上的取舍。不同传统对这些教导有着不同的理解。",
      "《薄伽梵歌》中的对话发生在战斗开始之前。此处的战斗、跪姿和光线变化属于艺术呈现，并非对事件时间顺序的逐一还原，也不是历史重建。",
      "场景包含不血腥的战斗画面以及有关死亡的讨论。"
    ],
    "meet": "故事中的声音",
    "voices": {
      "Sanjaya": {
        "role": "叙述者",
        "description": "持国王的顾问。他经毗耶娑赐予神视，向远离战场的国王转述克里希纳与阿周那的对话。",
        "location": "向国王讲述"
      },
      "Dhritarashtra": {
        "role": "国王",
        "description": "俱卢百子的父亲。他询问桑贾亚：他的儿子们与他们的堂兄弟为战争聚集之处，正在发生什么。",
        "location": "在宫廷中聆听"
      },
      "Arjun": {
        "role": "战士",
        "description": "般度五子之一。他是一位技艺高超的弓箭手，但望见战场对面的亲人和老师，他的心被悲痛淹没。",
        "location": "战车上"
      },
      "Krishna": {
        "role": "引导者",
        "description": "阿周那的朋友和御者。他成为阿周那的老师，并随着对话的展开，显露自己的神性。",
        "location": "战车上"
      }
    },
    "menu": "菜单",
    "journey": "旅程",
    "intro": "引言",
    "dialogue": "对话",
    "shloka": "颂诗",
    "meaning": "释义",
    "verseNote": "你可以浏览本章的任一偈颂。改编对话依据上方所示的偈颂范围。",
    "verseUnavailable": "颂诗未能加载。你仍可继续阅读对话。",
    "who": "谁在说话？",
    "back": "上一页",
    "next": "继续",
    "scene": "场景",
    "look": "环顾四周",
    "lookHelpDesktop": "拖动以转向 · 滚动以缩放 · 按住 Shift 拖动或使用 WASD 移动",
    "lookHelpTouch": "单指转向 · 双指移动 · 双指捏合或张开以缩放",
    "returnView": "回到战车",
    "viewFront": "面对面",
    "viewSide": "战车旁",
    "viewWide": "战场全景",
    "camera": "镜头",
    "light": "光线",
    "storyLight": "跟随故事",
    "dawn": "黎明",
    "day": "白昼",
    "dusk": "黄昏",
    "night": "夜晚",
    "volume": "战场音量",
    "gentleCamera": "固定镜头",
    "gentleNote": "故事继续时保持当前视角。关闭此项可让镜头平滑移动。",
    "pause": "暂停场景",
    "play": "恢复场景",
    "settings": "设置",
    "contents": "章节目录",
    "progress": "阅读进度",
    "complete": "对话在这里暂歇。",
    "audioPending": "配音暂未上线。",
    "reading": "阅读故事",
    "listening": "聆听",
    "source": "出处与背景",
    "close": "关闭",
    "moving": "正在抵达两军之间",
    "skipArrival": "跳过入场",
    "showDialogue": "显示对话",
    "hideDialogue": "隐藏对话",
    "readHint": "按自己的节奏继续。环顾四周不会翻页。",
    "chapter": "章",
    "preface": "对话开始之前",
    "soundError": "声音未能启动。请点按声音控件重试。",
    "experienceMode": "体验模式",
    "passageView": "段落视图",
    "moveCamera": "移动镜头",
    "moveLeft": "向左移动",
    "moveRight": "向右移动",
    "moveForward": "向前移动",
    "moveBack": "向后移动",
    "playback": "播放"
  },
  "fr": {
    "title": "Gita",
    "introLine": "Arjuna abaisse son arc.",
    "introBody": "Entre deux armées, il reconnaît ses proches, ses maîtres et ses amis parmi ceux qu’il doit combattre. Il se tourne vers Krishna.",
    "framing": "Deux branches d’une même famille se font face sur un immense champ de bataille. Arjuna, prince pandava, demande à son ami Krishna de conduire leur char entre les deux armées.",
    "language": "Choisissez votre langue",
    "enter": "Entrer dans le récit",
    "resume": "Poursuivre votre voyage",
    "restart": "Recommencer",
    "soundOn": "Sons du champ de bataille",
    "soundHint": "Le son commence à votre entrée dans le récit. Vous pouvez régler son volume ou le couper à tout moment.",
    "about": "À propos de cette adaptation",
    "notes": [
      "Une adaptation originale et abrégée de la Bhagavad-Gita. Le dialogue est adapté ; les shlokas sanskrits sont présentés séparément, avec leurs références de versets.",
      "Les traductions et les œuvres visuelles reflètent des choix d’interprétation. Les différentes traditions comprennent ces enseignements de différentes manières.",
      "La conversation de la Gita se déroule avant le début de la bataille. Les combats, les postures agenouillées et les changements de lumière présentés ici relèvent de la mise en scène artistique, et non d’une chronologie littérale ou d’une reconstitution historique.",
      "Les scènes comportent des combats sans violence graphique et des discussions sur la mort."
    ],
    "meet": "Les voix de ce récit",
    "voices": {
      "Sanjaya": {
        "role": "Le narrateur",
        "description": "Conseiller de Dhritarashtra. Doté de la vision divine par Vyasa, il rapporte la conversation de Krishna et d’Arjuna au roi, loin du champ de bataille.",
        "location": "Il raconte au roi"
      },
      "Dhritarashtra": {
        "role": "Le roi",
        "description": "Père des Kauravas. Il demande à Sanjaya ce qui se passe là où ses fils et leurs cousins se sont rassemblés pour la guerre.",
        "location": "Il écoute à la cour"
      },
      "Arjun": {
        "role": "Le guerrier",
        "description": "L’un des cinq frères Pandavas. C’est un archer accompli, mais la vue de sa famille et de ses maîtres de l’autre côté du champ de bataille le bouleverse.",
        "location": "Sur le char"
      },
      "Krishna": {
        "role": "Le guide",
        "description": "Ami d’Arjuna et conducteur de son char. Il devient son maître et révèle sa nature divine au fil de leur conversation.",
        "location": "Sur le char"
      }
    },
    "menu": "Menu",
    "journey": "Le voyage",
    "intro": "Introduction",
    "dialogue": "Dialogue",
    "shloka": "Shloka",
    "meaning": "Sens",
    "verseNote": "Vous pouvez consulter tous les versets de ce chapitre. Le dialogue adapté s’appuie sur la plage de versets indiquée ci-dessus.",
    "verseUnavailable": "Le shloka n’a pas pu être chargé. Vous pouvez poursuivre avec le dialogue.",
    "who": "Qui parle ?",
    "back": "Précédent",
    "next": "Continuer",
    "scene": "Scène",
    "look": "Regarder autour de vous",
    "lookHelpDesktop": "Glisser pour tourner · Faire défiler pour zoomer · Maj + glisser ou WASD pour se déplacer",
    "lookHelpTouch": "Un doigt pour tourner · Deux doigts pour se déplacer · Pincer pour zoomer",
    "returnView": "Revenir au char",
    "viewFront": "Face à face",
    "viewSide": "À côté du char",
    "viewWide": "Tout le champ de bataille",
    "camera": "Caméra",
    "light": "Lumière",
    "storyLight": "Suivre le récit",
    "dawn": "Aube",
    "day": "Jour",
    "dusk": "Crépuscule",
    "night": "Nuit",
    "volume": "Volume du champ de bataille",
    "gentleCamera": "Garder la caméra fixe",
    "gentleNote": "Conserve le point de vue actuel pendant le récit. Désactivez cette option pour laisser la caméra se déplacer en continu.",
    "pause": "Mettre la scène en pause",
    "play": "Reprendre la scène",
    "settings": "Réglages",
    "contents": "Chapitres",
    "progress": "Progression de lecture",
    "complete": "La conversation fait ici une pause.",
    "audioPending": "La narration n’est pas encore disponible.",
    "reading": "Lire le récit",
    "listening": "Écouter",
    "source": "Source et contexte",
    "close": "Fermer",
    "moving": "Arrivée entre les armées",
    "skipArrival": "Passer l’arrivée",
    "showDialogue": "Afficher le dialogue",
    "hideDialogue": "Masquer le dialogue",
    "readHint": "Poursuivez à votre rythme. Regarder autour de vous ne tourne pas la page.",
    "chapter": "Chapitre",
    "preface": "Avant la conversation",
    "soundError": "Le son n’a pas pu démarrer. Touchez la commande du son pour réessayer.",
    "experienceMode": "Mode d’expérience",
    "passageView": "Affichage du passage",
    "moveCamera": "Déplacer la caméra",
    "moveLeft": "Se déplacer vers la gauche",
    "moveRight": "Se déplacer vers la droite",
    "moveForward": "Avancer",
    "moveBack": "Reculer",
    "playback": "Lecture"
  }
};
