const en={read:'Read',listen:'Listen',preface:'Preface',before:'Before the conversation',chapter:'Chapter',contents:'The conversation',settings:'Your experience',language:'Language',speed:'Listening speed',ambience:'Field ambience',motion:'Reduce motion',pause:'Pause the scene',explore:'Explore Kurukshetra',return:'Return to the story',continue:'Continue',finish:'The end',meaning:'Within this passage',understand:'In simple terms',example:'In everyday life',context:'Context',reflection:'A question to carry',sanskrit:'Sanskrit',full:'Read this chapter',source:'Source',adaptation:'An original, abridged adaptation of the Bhagavad Gita.',missing:'Narration is being prepared.',ready:'Listen from here',playing:'',paused:'Paused',buffering:'Loading audio…',blocked:'Tap play to continue.',error:'Audio could not load. Press Play to try again.',ended:'The conversation rests here.',languageError:'This language could not load. Please try again.',play:'Play narration',pauseAudio:'Pause narration',previous:'Previous passage',next:'Next passage',close:'Close',show:'Show playback controls',scene:'Krishna and Arjun at Kurukshetra. Drag to look around.',audioPosition:'Narration position'};
const hi={read:'पढ़ें',listen:'सुनें',preface:'भूमिका',before:'संवाद से पहले',chapter:'अध्याय',contents:'संवाद',settings:'आपका अनुभव',language:'भाषा',speed:'सुनने की गति',ambience:'मैदान की ध्वनियाँ',motion:'गति कम करें',pause:'दृश्य रोकें',explore:'कुरुक्षेत्र देखें',return:'कथा में लौटें',continue:'आगे',finish:'समापन',meaning:'इस अंश का अर्थ',understand:'सरल शब्दों में',example:'रोज़मर्रा के जीवन में',context:'संदर्भ',reflection:'विचार के लिए एक प्रश्न',sanskrit:'संस्कृत',full:'यह अध्याय पढ़ें',source:'स्रोत',adaptation:'भगवद्गीता का एक मौलिक, संक्षिप्त रूपांतरण।',missing:'वाचन की तैयारी चल रही है।',ready:'यहाँ से सुनें',playing:'',paused:'रुका हुआ',buffering:'ऑडियो लोड हो रहा है…',blocked:'जारी रखने के लिए चलाएँ दबाएँ।',error:'ऑडियो लोड नहीं हुआ। फिर से चलाएँ।',ended:'संवाद यहाँ विश्राम लेता है।',languageError:'भाषा लोड नहीं हुई। फिर से प्रयास करें।',play:'वाचन चलाएँ',pauseAudio:'वाचन रोकें',previous:'पिछला अंश',next:'अगला अंश',close:'बंद करें',show:'सुनने के नियंत्रण दिखाएँ',scene:'कुरुक्षेत्र में कृष्ण और अर्जुन। चारों ओर देखने के लिए खींचें।',audioPosition:'वाचन की स्थिति'};
const ja={read:'読む',listen:'聴く',preface:'序章',before:'対話の前に',chapter:'章',contents:'対話',settings:'体験の設定',language:'言語',speed:'再生速度',ambience:'戦場の環境音',motion:'動きを抑える',pause:'場面を一時停止',explore:'クルクシェートラを見渡す',return:'物語に戻る',continue:'次へ',finish:'終わり',meaning:'この一節について',understand:'わかりやすく',example:'日々の暮らしでは',context:'背景',reflection:'心に留める問い',sanskrit:'サンスクリット語',full:'この章を読む',source:'出典',adaptation:'『バガヴァッド・ギーター』をもとにした独自の抄訳的翻案。',missing:'朗読を準備しています。',ready:'ここから聴く',playing:'',paused:'一時停止中',buffering:'音声を読み込み中…',blocked:'再生を押すと続きます。',error:'音声を読み込めませんでした。もう一度再生してください。',ended:'対話はここで静かに終わります。',languageError:'言語を読み込めませんでした。もう一度お試しください。',play:'朗読を再生',pauseAudio:'朗読を一時停止',previous:'前の一節',next:'次の一節',close:'閉じる',show:'再生コントロールを表示',scene:'クルクシェートラにいるクリシュナとアルジュナ。ドラッグして見渡せます。',audioPosition:'朗読の再生位置'};
const zh={read:'阅读',listen:'聆听',preface:'序言',before:'对话开始之前',chapter:'章',contents:'对话',settings:'体验设置',language:'语言',speed:'播放速度',ambience:'战场环境音',motion:'减少动态效果',pause:'暂停场景',explore:'探索俱卢之野',return:'返回故事',continue:'继续',finish:'终章',meaning:'读懂这一段',understand:'简单来说',example:'在日常生活中',context:'背景',reflection:'留在心中的问题',sanskrit:'梵文',full:'阅读本章',source:'出处',adaptation:'根据《薄伽梵歌》创作的原创节编改写。',missing:'朗读音频正在准备中。',ready:'从这里开始听',playing:'',paused:'已暂停',buffering:'正在加载音频…',blocked:'点击播放以继续。',error:'无法加载音频，请再次播放。',ended:'对话在此暂歇。',languageError:'无法加载此语言，请重试。',play:'播放朗读',pauseAudio:'暂停朗读',previous:'上一段',next:'下一段',close:'关闭',show:'显示播放控制',scene:'克里希纳与阿周那置身俱卢之野。拖动即可环顾四周。',audioPosition:'朗读进度'};
const fr={read:'Lire',listen:'Écouter',preface:'Préface',before:'Avant le dialogue',chapter:'Chapitre',contents:'Le dialogue',settings:'Votre expérience',language:'Langue',speed:'Vitesse de lecture',ambience:'Ambiance du champ',motion:'Réduire les mouvements',pause:'Mettre la scène en pause',explore:'Explorer Kurukshetra',return:'Revenir au récit',continue:'Continuer',finish:'Fin',meaning:'Au fil de ce passage',understand:'En quelques mots',example:'Dans la vie quotidienne',context:'Contexte',reflection:'Une question à garder',sanskrit:'Sanskrit',full:'Lire ce chapitre',source:'Source',adaptation:'Une adaptation originale et abrégée de la Bhagavad-Gītā.',missing:'La narration est en préparation.',ready:'Écouter à partir d’ici',playing:'',paused:'En pause',buffering:'Chargement de l’audio…',blocked:'Appuyez sur lecture pour continuer.',error:'Impossible de charger l’audio. Réessayez.',ended:'Le dialogue s’achève ici.',languageError:'Impossible de charger cette langue. Réessayez.',play:'Lire la narration',pauseAudio:'Mettre la narration en pause',previous:'Passage précédent',next:'Passage suivant',close:'Fermer',show:'Afficher les commandes de lecture',scene:'Krishna et Arjuna à Kurukshetra. Faites glisser pour regarder autour de vous.',audioPosition:'Position dans la narration'};
const extras=[
  [en,{kurukshetra:'Kurukshetra',prepare:'Preparing the scene…',sceneError:'The scene could not load. You can keep reading or reload.',reload:'Reload scene',keepReading:'Keep reading',fields:{clash:'Soldiers',cavalry:'Cavalry',elephants:'Elephants',wide:'Whole field'},fieldTitles:{clash:'At the front line',cavalry:'Across the open ground',elephants:'The war elephants',wide:'Between the two armies'}}],
  [hi,{kurukshetra:'कुरुक्षेत्र',prepare:'दृश्य तैयार हो रहा है…',sceneError:'दृश्य लोड नहीं हुआ। आप पढ़ना जारी रख सकते हैं या दोबारा लोड कर सकते हैं।',reload:'दृश्य फिर लोड करें',keepReading:'पढ़ना जारी रखें',fields:{clash:'सैनिक',cavalry:'घुड़सवार',elephants:'हाथी',wide:'पूरा मैदान'},fieldTitles:{clash:'युद्ध की अग्रिम पंक्ति',cavalry:'खुले मैदान में',elephants:'युद्ध के हाथी',wide:'दो सेनाओं के बीच'}}],
  [ja,{kurukshetra:'クルクシェートラ',prepare:'場面を準備しています…',sceneError:'場面を読み込めませんでした。読み進めるか、再読み込みできます。',reload:'場面を再読み込み',keepReading:'読み進める',fields:{clash:'兵士',cavalry:'騎兵',elephants:'戦象',wide:'戦場全体'},fieldTitles:{clash:'最前線で',cavalry:'開けた大地を渡って',elephants:'戦象たち',wide:'二つの軍勢の間で'}}],
  [zh,{kurukshetra:'俱卢之野',prepare:'正在准备场景…',sceneError:'无法加载场景。您可以继续阅读或重新加载。',reload:'重新加载场景',keepReading:'继续阅读',fields:{clash:'士兵',cavalry:'骑兵',elephants:'战象',wide:'整个战场'},fieldTitles:{clash:'在战斗前线',cavalry:'穿过开阔地带',elephants:'战象',wide:'两军之间'}}],
  [fr,{kurukshetra:'Kurukshetra',prepare:'Préparation de la scène…',sceneError:'Impossible de charger la scène. Vous pouvez continuer à lire ou la recharger.',reload:'Recharger la scène',keepReading:'Continuer à lire',fields:{clash:'Soldats',cavalry:'Cavalerie',elephants:'Éléphants',wide:'Tout le champ'},fieldTitles:{clash:'En première ligne',cavalry:'À travers la plaine',elephants:'Les éléphants de guerre',wide:'Entre les deux armées'}}]
];
for(const [target,values] of extras)Object.assign(target,values);
export const languages=['en','hi','ja','zh-Hans','fr'];
export const ui={en,hi,ja,'zh-Hans':zh,fr};
